### ISSUE TITLE
Implement a reusable cell queue like in UITableView

### ISSUE THREAD

**Issue by provideal** [provideal/MMGridView#1]

**Comment by itunyk** [comment]
It would be really cool if you do this. Thank you.

**Comment by provideal** [comment]
The grid is designed as a simple dashboard like menu, to hold only a small number of cells 5-20. Even with 50 cells the rendering performance is ~50fps on an iPhone4. I think for the purpose of MMGridView this is fast enough, and there is no need for a cell queue.
