### ISSUE TITLE
use as a vertical scrolling view

### ISSUE THREAD

**Issue by reejosamuel** [provideal/MMGridView#15]
I want to be able to use this as a vertical scrolling view instead of a horizontal paged. How?

**Comment by provideal** [comment]
Not possible, sorry.

**Comment by tbass134** [comment]
its really easy to change it to vertical.
Inside MMGridView.m,
line 121:
change to
CGSize contentSize = CGSizeMake(gridBounds.size.width, gridBounds.size.height \* (round(noOfCols *noOfRows)-1));
im just changing the height of the scrollView to the amount of rows and cols. In my case i have "numberOfRows" and "numberOfColumns" set to 2. (line 81, and 82)

then on line 133 where it says"NSInteger page = (int)floor((float)i / (float)cellsPerPage);"
just set the page var to 0

thats it!

**Comment by realalien** [comment]
For the tbass134's vertical scroll monkey patching, the srollView looks nicer if 

```
CGSize contentSize = CGSizeMake(gridBounds.size.width, (noOfRows + 1) * cellBounds.size.height );
```

**Comment by zabumba69** [comment]
contentSize in vertical scroll is:

NSUInteger numberOfCells = [self.dataSource numberOfCellsInGridView:self];
NSUInteger numberOfLines = numberOfCells/numberOfColumns;
CGSize contentSize = CGSizeMake(gridBounds.size.width, numberOfLines \* cellBounds.size.height);
