### ISSUE TITLE
Load Images from the Server

### ISSUE THREAD

**Issue by ajaysharmalike** [provideal/MMGridView#16]
Can you please help me with some code, I would like to reload this Grid with using the images downloaded from the server.Similar to Lazy Loading.

**Comment by renspr** [comment]
Hi,

this has nothing to do with the grid view implementation. All u need is to load and set the images in the gridView:cellAtIndex: delegate method, but instead loading the images from the bundle u can use proper code to instantiate the UIImage with data from a remote URL. You may also create your own cell implementation by overriding MMGridViewCell that can be instantiated with an image URL and handles the loading and caching by its own. The second one is the cleaner way I think.

Regards, René
