### ISSUE TITLE
How to change the image size to auto-fill the cell backgroundcolor?

### ISSUE THREAD

**Issue by scottliyq** [provideal/MMGridView#17]
Hi, 

In the cellAtIndex method, I use the below code to set the cell background color. The problem is that the image may be repeated if the size is not proper. Can you please advise a way to avoid image repeating? Sorry, it may be not related to the MMGridView, appreciate your help in advance.    

CGSize newSize = CGSizeMake(myCachedImage.size.width_0.3, myCachedImage.size.height_0.3);
    UIGraphicsBeginImageContextWithOptions(newSize, NO, 0.0);
    [myCachedImage drawInRect: CGRectMake(0, 0, newSize.width, newSize.height)];
    UIImage *smallLoadingImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext(); 

```
cell.backgroundView.backgroundColor = [UIColor colorWithPatternImage:smallLoadingImage];
```

**Comment by renspr** [comment]
I updated the default cell to provide a imageView property of type UIImageView. Instead of setting the background color of the backgroundView set the UIImage on the image view.
