### ISSUE TITLE
ARS compatiblity

### ISSUE THREAD

**Issue by hden** [provideal/MMGridView#18]
Anyone interested in making this compatible with iOS5 automatic reference count?
I have convert the code with the xcode automatic conversion, but I'm not sure if I tweaked the code right. Can anyone give me some suggestion?

**Comment by nolanRatu** [comment]
Select your project target -> Buildphases -> Double click all the MMGrid .m files and add -fno-objc-arc. If you still get errors restart xcode.

**Comment by renspr** [comment]
Converted to ARC.
