### ISSUE TITLE
MMGridView Xcode Project No errors but does not run in Simulator

### ISSUE THREAD

**Issue by CapeFurSeal** [provideal/MMGridView#20]
Hello there.

I downloaded the MMGridView Sample project. It has No errors and builds successfully, however when I push the RUN button, The Simulator does not launch the app. It just does nothing, and the app does not show it is running.

Please help.

Thank you.

**Comment by CapeFurSeal** [comment]
I just edited the Project Schema to Run. Fixed. Thanks.

**Comment by renspr** [comment]
I updated the XCode project settings. Should be good now.
