### ISSUE TITLE
loading UIWebView into cell.backgroundView not working

### ISSUE THREAD

**Issue by md347** [provideal/MMGridView#3]
i have sat here trying to populate the cell.backgroundView with a UIWebView with no success. The data is there because i can assign the cell.textLabel the address of the web page. how do i actually show the 'webPage' in the cell.backgroundView?

**Comment by provideal** [comment]
Hi,

I never tried or think about to use a UIWebView (a really heavy component) as the background view of a cell. To use a component like UIWebView is definitely not the intention behind cell.backgroundView. Can you please explain what exactly you are trying to create and why you are want to use UIWebView as the background view of a cell. Please provide some demo code.

Regards,

René

**Comment by md347** [comment]
i managed to get it to work with a web view, but i'm getting a lot of memory issues. after struggling to get the webView to load into your 'cell' i then realised that the memory issues are there without any of my code added.

**Comment by bamlhs** [comment]
Hello,

I want to show in every cell  UIWebView that contain yotube embed code. but it doesn't work .

thanks

**Comment by provideal** [comment]
I don't think it's a good idea to have a grid of UIWebViews that embed YouTube videos. Why not generating images of the video and use that images as the background of a cell? When the user tabs the cell, navigate to a view that plays the video.

**Comment by bamlhs** [comment]
it's good idea but how can I do "When the user tabs the cell, navigate to a view that plays the video." ?
I mean playing YouTube directly in view?

thanks

**Comment by provideal** [comment]
The example app shows how to navigate to a view. This is standard ios business. on that view u may use your webview idea or u can play the video directly without open up an extra view by calling the youtube url directly. ios handles the URL schema automatically. Look here http://stackoverflow.com/questions/5439179/how-do-i-launch-a-youtube-video-in-my-iphone-app

**Comment by bamlhs** [comment]
Thank you
