### ISSUE TITLE
Buttons as cell subviews

### ISSUE THREAD

**Issue by provideal** [provideal/MMGridView#6]
Implement support for "interactive" controls like UIButton as cell subviews.

**Comment by itunyk** [comment]
Hi René,
I deleted MMGridViewDefaulCell and all my buttons, images, labels I've inserted inside MMGridCell and it work's for me.

**Comment by provideal** [comment]
Create ur own subclasses of MMGridViewCell (MMGridViewDefaultCell is more an example)
