### ISSUE TITLE
Works fine with iPad

### ISSUE THREAD

**Issue by pailoro** [provideal/MMGridView#7]
If I implement these classes for iPad, it will works fine with the basics configuration, or I will have to change the GridView classes?

Thanks!

**Comment by provideal** [comment]
Hi. I actually never tried on iPad (I created the grid as a component for an iPhone only app). There is nothing special in the code that prevent it from running on iPad. Please give it a try and let me know if it is working. In case you make changes for iPad please consider to create a pull request.

Regards, René
